#!/usr/bin/env bash
# Generate a wrapper in /usr/local/bin for every tool listed in tools.tsv.
#
# Every tool is installed into a conda environment under /opt/conda/envs and is
# started the same way: a small wrapper puts that environment's bin directory
# first on PATH (so tools that call their own helper binaries keep working) and
# execs the real program. Users never activate an environment or load a module.
#
# The build fails if a declared command is missing, so tools.tsv cannot drift
# away from what is actually installed.
set -euo pipefail

TSV="${1:-/opt/tools.tsv}"
ENV_ROOT=/opt/conda/envs
BIN_DIR=/usr/local/bin

count=0
while IFS=$'\t' read -r cmd env version description; do
    [ -z "${cmd:-}" ] && continue
    case "$cmd" in \#*) continue ;; esac

    target="${ENV_ROOT}/${env}/bin/${cmd}"
    if [ ! -x "$target" ]; then
        echo "ERROR: ${target} does not exist or is not executable (declared in ${TSV})" >&2
        exit 1
    fi

    cat > "${BIN_DIR}/${cmd}" <<WRAPPER
#!/usr/bin/env bash
# Auto-generated by make-wrappers.sh - runs ${cmd} (${version}) from the '${env}' environment.
export PATH="${ENV_ROOT}/${env}/bin:\${PATH}"
exec "${target}" "\$@"
WRAPPER
    chmod 755 "${BIN_DIR}/${cmd}"
    count=$((count + 1))
done < "$TSV"

echo "created ${count} tool wrappers in ${BIN_DIR}"
